import AppKit
import SwiftUI

/// Raycast-style clipboard history: remembers text you copy, searchable from the palette (⌃⌥V).
/// Passwords and other items marked private by the app that copied them are never kept.
@MainActor
final class ClipboardHistory: ObservableObject {
    struct Entry: Codable, Identifiable, Equatable {
        var id = UUID()
        var text: String
        var date: Date
        var app: String?
        var pinned = false
    }

    @Published var enabled: Bool { didSet { UserDefaults.standard.set(enabled, forKey: "clipEnabled"); enabled ? start() : stop() } }
    @Published var keepDays: Int { didSet { UserDefaults.standard.set(keepDays, forKey: "clipDays"); prune() } }
    @Published private(set) var entries: [Entry] = []

    static let maxEntries = 500
    /// Pasteboard types that mean "don't record this" (nspasteboard.org conventions, used by password managers).
    static let skipTypes: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                                         "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
    static let skipApps: Set<String> = ["com.1password.1password", "com.bitwarden.desktop", "com.apple.Passwords",
                                        "com.apple.keychainaccess"]

    private var timer: Timer?
    private var lastChange = NSPasteboard.general.changeCount
    private let url = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        .appendingPathComponent("FanCurve/clipboard-history.json")

    init() {
        enabled = UserDefaults.standard.object(forKey: "clipEnabled") as? Bool ?? true
        keepDays = UserDefaults.standard.object(forKey: "clipDays") as? Int ?? 7
        entries = (try? JSONDecoder().decode([Entry].self, from: Data(contentsOf: url))) ?? []
        prune()
        if enabled { start() }
    }

    private func start() {
        guard timer == nil else { return }
        lastChange = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer?.tolerance = 0.2
    }

    private func stop() { timer?.invalidate(); timer = nil }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount
        let types = Set((pb.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.skipTypes) else { return }
        let front = NSWorkspace.shared.frontmostApplication
        guard !Self.skipApps.contains(front?.bundleIdentifier ?? "") else { return }
        guard let text = pb.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              text.count < 100_000 else { return }
        add(text, app: front?.localizedName)
    }

    func add(_ text: String, app: String?) {
        let pinned = entries.first { $0.text == text }?.pinned ?? false
        entries.removeAll { $0.text == text }
        entries.insert(Entry(text: text, date: Date(), app: app, pinned: pinned), at: 0)
        prune()
    }

    func delete(_ e: Entry) { entries.removeAll { $0.id == e.id }; save() }
    func togglePin(_ e: Entry) { if let i = entries.firstIndex(of: e) { entries[i].pinned.toggle(); save() } }
    func clear() { entries.removeAll { !$0.pinned }; save() }

    /// Puts the entry back on the clipboard and pastes it into the app that was in front.
    func paste(_ e: Entry) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(e.text, forType: .string)
        lastChange = pb.changeCount
        add(e.text, app: e.app)
        Paster.key(9, flags: .maskCommand)   // ⌘V
    }

    private func prune() {
        let cutoff = Date().addingTimeInterval(-Double(keepDays) * 86_400)
        entries = entries.filter { $0.pinned || $0.date > cutoff }
        if entries.count > Self.maxEntries {
            let pinned = entries.filter(\.pinned)
            entries = pinned + entries.filter { !$0.pinned }.prefix(Self.maxEntries - pinned.count)
        }
        save()
    }

    private func save() {
        try? FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try? JSONEncoder().encode(entries).write(to: url, options: [.atomic, .completeFileProtection])
    }
}

/// Palette view of the clipboard history.
@MainActor
final class ClipboardSource: PanelSource {
    let history: ClipboardHistory
    init(history: ClipboardHistory) { self.history = history }

    var placeholder: String { "Search clipboard history…" }

    func items(for query: String) -> [PanelItem] {
        guard history.enabled else {
            return [PanelItem(id: "off", title: "Turn On Clipboard History", subtitle: "Remembers text you copy, on this Mac only",
                              symbol: "doc.on.clipboard", tint: .blue) { [history] in history.enabled = true; return false }]
        }
        let sorted = history.entries.filter(\.pinned) + history.entries.filter { !$0.pinned }
        let items = sorted.map { e in
            PanelItem(id: e.id.uuidString, section: e.pinned ? "Pinned" : "Recent",
                      title: e.text.trimmingCharacters(in: .whitespacesAndNewlines).replacingOccurrences(of: "\n", with: " ⏎ "),
                      subtitle: [e.app, e.date.formatted(.relative(presentation: .named))].compactMap { $0 }.joined(separator: " · "),
                      accessory: e.text.count > 60 ? "\(e.text.count) chars" : nil,
                      symbol: e.pinned ? "pin.fill" : Self.symbol(for: e.text), tint: .blue,
                      actions: [PanelAction(key: "p", display: "⌘P", label: e.pinned ? "Unpin" : "Pin") { [history] in history.togglePin(e) },
                                PanelAction(key: "\u{7f}", display: "⌘⌫", label: "Delete") { [history] in history.delete(e) }]) { [history] in
                LauncherPanel.shared.returnToPreviousApp { history.paste(e) }
                return true
            }
        }
        var out = items.filtered(query)
        if query.isEmpty && !history.entries.isEmpty {
            out.append(PanelItem(id: "clip.clear", section: "Clipboard", title: "Clear Clipboard History", subtitle: "Pinned items are kept",
                                 symbol: "trash", tint: .red) { [history] in history.clear(); return false })
        }
        if out.isEmpty {
            out = [PanelItem(id: "none", title: query.isEmpty ? "Nothing copied yet" : "No matches", symbol: "doc.on.clipboard", tint: .blue) { true }]
        }
        return out
    }

    private static func symbol(for text: String) -> String {
        if text.hasPrefix("http://") || text.hasPrefix("https://") { return "link" }
        if text.contains("\n") { return "text.alignleft" }
        return "doc.on.clipboard"
    }
}
